// Render a restore map (restore.mjs's markdown) to a self-contained HTML worklist.
//
//   node oracle/analytics/restore-html.mjs [report.md] [-o out.html]
//     report.md   default: the newest findings/*-driver-restore.md
//     -o          default: the input path with .html
//
// Why a second file rather than plain markdown: the restore is done with the game open, and a
// browser shows a .md as unstyled text. This adds a tick box per line with a progress bar, greys out
// a champion once every line under it is ticked, and gives a sidebar to jump between them.
//
// The page is SELF-CONTAINED — CSS and JS inlined, no external requests — because it is opened over
// a \\wsl.localhost UNC path where a CDN reference is both a privacy leak and a broken-offline risk.
//
// Ticks are a local scratch aid, NOT the source of truth. The snapshots are: re-running restore.mjs
// re-derives what is left from the DB. Ticks are keyed on the artifact id so they survive a
// regeneration even though champion ordering shifts as slots close.

import { readFileSync, readdirSync, realpathSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const FINDINGS = fileURLToPath(new URL("./findings", import.meta.url));

const ESC = { "&": "&amp;", "<": "&lt;", ">": "&gt;" };
const esc = (s) => s.replace(/[&<>]/g, (c) => ESC[c]);

// Inline spans: `code` first so bold markers inside a code span are left alone.
export function inline(s) {
  return esc(s)
    .replace(/`([^`]+)`/g, (_, c) => `<code>${c}</code>`)
    .replace(/\*\*([^*]+)\*\*/g, (_, b) => `<strong>${b}</strong>`);
}

// A deliberately small markdown subset — headings, nested bullets, bold, inline code — rather than a
// parser dependency. The input is not arbitrary markdown: it is generated by restore.mjs next door,
// so the shape is fixed and known, and `marked` is a packages/web dependency that an oracle/ script
// would only reach through npm hoisting.
export function toHtml(md) {
  const out = [];
  let list = 0;                                     // open <ul> depth
  const closeTo = (depth) => { while (list > depth) { out.push("</ul>"); list--; } };
  for (const raw of md.split("\n")) {
    const h = /^(#{1,3}) (.+)$/.exec(raw);
    if (h) { closeTo(0); out.push(`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`); continue; }
    const li = /^(\s*)- (.+)$/.exec(raw);
    if (li) {
      const depth = Math.floor(li[1].length / 2) + 1;
      // A nested list opens INSIDE the line above it, so the parent <li> is left unclosed until the
      // nesting unwinds — that containment is what the page's checkbox pass keys on.
      while (list < depth) { out.push("<ul>"); list++; }
      closeTo(depth);
      out.push(`<li>${inline(li[2])}`);
      continue;
    }
    if (!raw.trim()) { closeTo(0); continue; }
    // A bare continuation line belongs to whatever is open above it.
    if (list > 0) out.push(` ${inline(raw.trim())}`);
    else out.push(`<p>${inline(raw.trim())}</p>`);
  }
  closeTo(0);
  return out.join("\n");
}

export function page(md, title) {
  const toc = [...md.matchAll(/^(##|###) (.+)$/gm)]
    .map(([, h, text]) => ({ level: h.length, text }));
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(title)}</title>
<style>
:root {
  --bg: #fbfaf8; --panel: #fff; --ink: #1c1b19; --muted: #6b6862; --line: #e3dfd8;
  --accent: #8a5a2b; --accent-soft: #f0e6da; --done: #7a8f6a;
  --mono: ui-monospace, "SF Mono", "Cascadia Mono", Menlo, Consolas, monospace;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    --bg: #171614; --panel: #1f1e1b; --ink: #ece8e1; --muted: #9a958c; --line: #333029;
    --accent: #d9a066; --accent-soft: #2c2620; --done: #9db98a;
  }
}
:root[data-theme="dark"] {
  --bg: #171614; --panel: #1f1e1b; --ink: #ece8e1; --muted: #9a958c; --line: #333029;
  --accent: #d9a066; --accent-soft: #2c2620; --done: #9db98a;
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--bg); color: var(--ink);
  font: 16px/1.65 -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
}
.wrap { display: grid; grid-template-columns: minmax(0, 1fr); max-width: 1240px; margin: 0 auto; }
@media (min-width: 1000px) { .wrap { grid-template-columns: 268px minmax(0, 1fr); gap: 32px; } }
aside {
  display: none; padding: 28px 0 60px 20px; align-self: start;
  position: sticky; top: 0; max-height: 100vh; overflow-y: auto;
}
@media (min-width: 1000px) { aside { display: block; } }
aside .head {
  font-size: 11px; letter-spacing: .09em; text-transform: uppercase;
  color: var(--muted); margin: 0 0 10px;
}
aside a {
  display: block; padding: 3px 10px; border-radius: 5px; text-decoration: none;
  color: var(--muted); font-size: 13px; line-height: 1.4;
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap;
}
aside a:hover { background: var(--accent-soft); color: var(--ink); }
aside a.lvl3 { padding-left: 20px; font-size: 12.5px; }
aside a.lvl2 { margin-top: 12px; font-weight: 650; color: var(--ink); }
aside a.cleared { color: var(--done); }
aside a.cleared::after { content: " \\2713"; }
.status {
  position: sticky; top: 0; z-index: 5; background: var(--bg);
  border-bottom: 1px solid var(--line); padding: 10px 20px;
  display: flex; align-items: center; gap: 14px; flex-wrap: wrap;
}
.status b { font-variant-numeric: tabular-nums; }
.bar {
  flex: 1 1 160px; height: 6px; min-width: 120px;
  background: var(--line); border-radius: 3px; overflow: hidden;
}
.bar i { display: block; height: 100%; width: 0; background: var(--done); transition: width .2s; }
.status button {
  font: inherit; font-size: 13px; padding: 3px 11px; cursor: pointer;
  background: var(--panel); color: var(--muted);
  border: 1px solid var(--line); border-radius: 6px;
}
.status button:hover { color: var(--ink); border-color: var(--accent); }
main { padding: 0 20px 100px; min-width: 0; }
h1 { font-size: 27px; line-height: 1.25; margin: 30px 0 6px; letter-spacing: -.015em; }
h2 {
  font-size: 20px; margin: 52px 0 4px; padding-bottom: 8px;
  border-bottom: 2px solid var(--line); letter-spacing: -.01em;
}
h3 {
  font-size: 15.5px; margin: 30px 0 2px; padding: 9px 13px;
  background: var(--panel); border: 1px solid var(--line);
  border-left: 3px solid var(--accent); border-radius: 0 7px 7px 0;
}
h3.cleared { border-left-color: var(--done); opacity: .58; }
p { margin: 10px 0; }
h1 + p, h2 + p { color: var(--muted); font-size: 14.5px; }
code {
  font-family: var(--mono); font-size: .855em;
  background: var(--accent-soft); padding: 1.5px 5px; border-radius: 4px;
}
ul { list-style: none; padding-left: 0; margin: 10px 0; }
main > ul { padding-left: 4px; }
main > ul > li { margin: 5px 0; padding-left: 17px; position: relative; color: var(--muted); }
main > ul > li::before { content: "\\2014"; position: absolute; left: 0; color: var(--line); }
main > ul > li strong { color: var(--ink); }
li.slot {
  margin: 3px 0; padding: 7px 11px 7px 34px; position: relative;
  border-radius: 7px; border: 1px solid transparent;
}
li.slot::before { content: none; }
li.slot:hover { background: var(--panel); border-color: var(--line); }
li.slot > input {
  position: absolute; left: 10px; top: 11px; margin: 0;
  width: 15px; height: 15px; accent-color: var(--done); cursor: pointer;
}
li.slot.done { opacity: .42; }
li.slot.done > .line { text-decoration: line-through; text-decoration-thickness: 1px; }
li.slot .line { font-size: 14.5px; }
li.slot ul { margin: 2px 0 0; }
li.slot li {
  font-family: var(--mono); font-size: 12.4px; line-height: 1.5;
  color: var(--muted); padding: 2px 0;
}
li.slot li::before { content: none; }
li.slot li strong { color: var(--accent); font-weight: 600; }
</style>
</head>
<body>
<div class="wrap">
<aside>
  <p class="head">Sections</p>
  <nav id="toc">
${toc.map((t) => `    <a class="lvl${t.level}" href="#h-${t.level}-${
  encodeURIComponent(t.text)}">${esc(t.text)}</a>`).join("\n")}
  </nav>
</aside>
<div>
  <div class="status">
    <span><b id="done">0</b> / <b id="total">0</b> put back</span>
    <span class="bar"><i id="fill"></i></span>
    <button id="reset" type="button">Clear ticks</button>
  </div>
  <main>
${toHtml(md)}
  </main>
</div>
</div>
<script>
// Anchor headings to match the sidebar links, which were built from the same source text, and index
// the links by target id. A map rather than a per-paint querySelector: it avoids escaping a
// user-derived id into a selector (CSS.escape is not universally present) and avoids re-querying the
// whole sidebar once per heading on every tick.
var tocByTarget = {};
document.querySelectorAll("#toc a").forEach(function (a) {
  tocByTarget[a.getAttribute("href").slice(1)] = a;
});
document.querySelectorAll("main h2, main h3").forEach(function (h) {
  h.id = "h-" + h.tagName[1] + "-" + encodeURIComponent(h.textContent);
});

// Storage is best-effort. A page opened over file:// (or \\\\wsl.localhost, which is how this one is
// meant to be opened) can have an opaque origin, and touching localStorage then THROWS rather than
// returning null. Unguarded that kills the whole script and the page loses every checkbox, so ticks
// fall back to memory-only for the session.
var KEY = "restore:" + document.title;
var store = (function () {
  try {
    var probe = "__t";
    localStorage.setItem(probe, probe);
    localStorage.removeItem(probe);
    return {
      get: function () { return localStorage.getItem(KEY); },
      set: function (v) { localStorage.setItem(KEY, v); },
      clear: function () { localStorage.removeItem(KEY); },
      ok: true,
    };
  } catch (e) {
    return { get: function () { return null; }, set: function () {}, clear: function () {}, ok: false };
  }
})();

var state = new Set();
try { state = new Set(JSON.parse(store.get() || "[]")); } catch (e) { /* corrupt value: start clean */ }
var rows = [];

document.querySelectorAll("main ul > li").forEach(function (li) {
  var nested = li.querySelector(":scope > ul");
  if (!nested) return;
  var m = nested.textContent.match(/#(\\d+)/);
  if (!m) return;
  li.classList.add("slot");
  // Wrap the slot's own text (everything before the nested list) so it can be struck through.
  var line = document.createElement("span");
  line.className = "line";
  while (li.firstChild !== nested) line.appendChild(li.firstChild);
  li.insertBefore(line, nested);

  var box = document.createElement("input");
  box.type = "checkbox";
  // An item appears twice when it is both a piece to put back and one to strip, so the tick key
  // counts prior occurrences of the same id rather than using the id alone.
  var seen = rows.filter(function (r) { return r.id === m[1]; }).length;
  var uniq = m[1] + ":" + seen;
  box.checked = state.has(uniq);
  li.classList.toggle("done", box.checked);
  box.addEventListener("change", function () {
    if (box.checked) state.add(uniq); else state.delete(uniq);
    li.classList.toggle("done", box.checked);
    store.set(JSON.stringify(Array.from(state)));
    paint();
  });
  li.insertBefore(box, line);
  rows.push({ id: m[1], li: li, box: box });
});

function paint() {
  var done = rows.filter(function (r) { return r.box.checked; }).length;
  document.getElementById("done").textContent = done;
  document.getElementById("total").textContent = rows.length;
  document.getElementById("fill").style.width =
    (rows.length ? done / rows.length * 100 : 0) + "%";
  document.querySelectorAll("main h3").forEach(function (h) {
    var mine = [];
    for (var n = h.nextElementSibling; n && n.tagName !== "H3" && n.tagName !== "H2";
         n = n.nextElementSibling) {
      mine.push.apply(mine, n.querySelectorAll("li.slot"));
    }
    var cleared = mine.length > 0 && mine.every(function (li) {
      return li.classList.contains("done");
    });
    h.classList.toggle("cleared", cleared);
    var link = tocByTarget[h.id];
    if (link) link.classList.toggle("cleared", cleared);
  });
}

document.getElementById("reset").addEventListener("click", function () {
  state.clear();
  store.clear();
  rows.forEach(function (r) { r.box.checked = false; r.li.classList.remove("done"); });
  paint();
});
paint();
// Say so rather than letting ticks look persistent when they are not.
if (!store.ok) {
  document.getElementById("reset").insertAdjacentHTML("afterend",
    '<span style="color:var(--muted);font-size:12.5px">ticks not saved (storage blocked)</span>');
}
</script>
</body>
</html>
`;
}

function newestReport() {
  const hits = readdirSync(FINDINGS).filter((f) => /-driver-restore\.md$/.test(f)).sort();
  return hits.length ? `${FINDINGS}/${hits[hits.length - 1]}` : null;
}

function main() {
  const argv = process.argv.slice(2);
  let src = null, out = null;
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "-o") out = argv[++i];
    else if (argv[i]) src = argv[i];
  }
  src = src ?? newestReport();
  if (!src) {
    console.error(`no *-driver-restore.md in ${FINDINGS}; run restore.mjs first`);
    process.exit(1);
  }
  const md = readFileSync(src, "utf8");
  const h1 = /^# (.+)$/m.exec(md);
  const title = h1 ? h1[1] : "Gear restore map";
  const dest = out ?? src.replace(/\.md$/, ".html");
  writeFileSync(dest, page(md, title));
  console.log(`wrote ${dest}`);
}

if (process.argv[1] && realpathSync(process.argv[1]) === fileURLToPath(import.meta.url)) main();
